// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"
)

const countCategoryTransactions = `-- name: CountCategoryTransactions :one
SELECT COUNT(*) FROM transactions WHERE category_id = ?
`

func (q *Queries) CountCategoryTransactions(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryTransactions, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories(name, type)
VALUES (?, ?)
`

type CreateCategoryParams struct {
	Name string
	Type string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.Name, arg.Type)
	return err
}

const deleteUnusedCategory = `-- name: DeleteUnusedCategory :execrows
DELETE FROM categories
WHERE categories.id = ?
AND NOT EXISTS (SELECT 1 FROM transactions WHERE transactions.category_id = ?)
`

type DeleteUnusedCategoryParams struct {
	ID         int64
	CategoryID int64
}

func (q *Queries) DeleteUnusedCategory(ctx context.Context, arg DeleteUnusedCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedCategory, arg.ID, arg.CategoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editCategory = `-- name: EditCategory :exec
UPDATE categories SET name = ?,
type = ? WHERE id = ?
`

type EditCategoryParams struct {
	Name string
	Type string
	ID   int64
}

func (q *Queries) EditCategory(ctx context.Context, arg EditCategoryParams) error {
	_, err := q.db.ExecContext(ctx, editCategory, arg.Name, arg.Type, arg.ID)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, type, created_at FROM categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
