// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Category struct {
	ID        int64
	Name      string
	Type      string
	CreatedAt string
}

type Transaction struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
}
