// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactins.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE   t.description LIKE '%' || ? || '%'
    OR c.name LIKE '%' || ? || '%'
`

type CountTransactionsParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (category_id, description,
    amount)
VALUES(?, ?, ?)
RETURNING id, category_id, description, amount, transaction_date
`

type CreateTransactionParams struct {
	CategoryID  int64
	Description string
	Amount      int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.CategoryID, arg.Description, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.TransactionDate,
	)
	return i, err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT t.id, t.category_id, t.description,
t.amount, t.transaction_date,
c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE   t.description LIKE '%' || ? || '%'
    OR c.name LIKE '%' || ? || '%'
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetAllTransactionsParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
	Limit   int64
	Offset  int64
}

type GetAllTransactionsRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetAllTransactions(ctx context.Context, arg GetAllTransactionsParams) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByDateRange = `-- name: GetTransactionByDateRange :many
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE t.transaction_date >= ?
AND t.transaction_date < ? 
ORDER BY t.transaction_date DESC, t.id DESC
`

type GetTransactionByDateRangeParams struct {
	TransactionDate   string
	TransactionDate_2 string
}

type GetTransactionByDateRangeRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionByDateRange(ctx context.Context, arg GetTransactionByDateRangeParams) ([]GetTransactionByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionByDateRange, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionByDateRangeRow
	for rows.Next() {
		var i GetTransactionByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE t.id = ?
`

type GetTransactionByIDRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.TransactionDate,
		&i.CategoryName,
		&i.CategoryType,
	)
	return i, err
}

const getTransactionsByCategoryID = `-- name: GetTransactionsByCategoryID :many
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE t.category_id = ?
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetTransactionsByCategoryIDParams struct {
	CategoryID int64
	Limit      int64
	Offset     int64
}

type GetTransactionsByCategoryIDRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionsByCategoryID(ctx context.Context, arg GetTransactionsByCategoryIDParams) ([]GetTransactionsByCategoryIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCategoryID, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByCategoryIDRow
	for rows.Next() {
		var i GetTransactionsByCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByCategoryType = `-- name: GetTransactionsByCategoryType :many
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE c.type = ?
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetTransactionsByCategoryTypeParams struct {
	Type   string
	Limit  int64
	Offset int64
}

type GetTransactionsByCategoryTypeRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionsByCategoryType(ctx context.Context, arg GetTransactionsByCategoryTypeParams) ([]GetTransactionsByCategoryTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCategoryType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByCategoryTypeRow
	for rows.Next() {
		var i GetTransactionsByCategoryTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET description = ?,
    amount = ?
WHERE id = ?
RETURNING id, category_id, description, amount, transaction_date
`

type UpdateTransactionParams struct {
	Description string
	Amount      int64
	ID          int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction, arg.Description, arg.Amount, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.TransactionDate,
	)
	return i, err
}
