// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactins.sql

package sqlc

import (
	"context"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE   t.description LIKE '%' || CAST(?1 AS TEXT) || '%'
    OR c.name LIKE '%' || CAST(?1 AS TEXT) || '%'
`

func (q *Queries) CountTransactions(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByCategoryID = `-- name: CountTransactionsByCategoryID :one
SELECT COUNT(*)
FROM transactions
WHERE category_id = ?
`

func (q *Queries) CountTransactionsByCategoryID(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByCategoryID, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByCategoryType = `-- name: CountTransactionsByCategoryType :one
SELECT COUNT(*)
FROM transactions
JOIN categories c ON transactions.category_id = c.id
WHERE c.type = ?
`

func (q *Queries) CountTransactionsByCategoryType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByCategoryType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByDateRange = `-- name: CountTransactionsByDateRange :one
SELECT COUNT(*)
FROM transactions
WHERE transaction_date >= ?
AND transaction_date < ?
`

type CountTransactionsByDateRangeParams struct {
	TransactionDate   string
	TransactionDate_2 string
}

func (q *Queries) CountTransactionsByDateRange(ctx context.Context, arg CountTransactionsByDateRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByDateRange, arg.TransactionDate, arg.TransactionDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (category_id, description,
    amount)
VALUES(?, ?, ?)
`

type CreateTransactionParams struct {
	CategoryID  int64
	Description string
	Amount      int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction, arg.CategoryID, arg.Description, arg.Amount)
	return err
}

const editTransaction = `-- name: EditTransaction :exec
UPDATE transactions
SET description = ?,
    amount = ?
WHERE id = ?
`

type EditTransactionParams struct {
	Description string
	Amount      int64
	ID          int64
}

func (q *Queries) EditTransaction(ctx context.Context, arg EditTransactionParams) error {
	_, err := q.db.ExecContext(ctx, editTransaction, arg.Description, arg.Amount, arg.ID)
	return err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT t.id, t.category_id, t.description,
t.amount, t.transaction_date,
c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE   t.description LIKE '%' || CAST(?3 AS TEXT) || '%'
    OR c.name LIKE '%' || CAST(?3 AS TEXT) || '%'
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetAllTransactionsParams struct {
	Search string
	Limit  int64
	Offset int64
}

type GetAllTransactionsRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetAllTransactions(ctx context.Context, arg GetAllTransactionsParams) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions, arg.Search, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryBreakdownByDateRange = `-- name: GetCategoryBreakdownByDateRange :many
SELECT c.id AS category_id,
    c.name AS category_name,
    c.type AS category_type,
    CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) AS total,
    COUNT(t.id) AS transaction_count
FROM categories c
LEFT JOIN transactions t
    ON t.category_id = c.id
    AND t.transaction_date >= ?
    AND t.transaction_date < ?
GROUP BY c.id, c.name, c.type
ORDER BY c.type ASC, total DESC
`

type GetCategoryBreakdownByDateRangeParams struct {
	TransactionDate   string
	TransactionDate_2 string
}

type GetCategoryBreakdownByDateRangeRow struct {
	CategoryID       int64
	CategoryName     string
	CategoryType     string
	Total            int64
	TransactionCount int64
}

func (q *Queries) GetCategoryBreakdownByDateRange(ctx context.Context, arg GetCategoryBreakdownByDateRangeParams) ([]GetCategoryBreakdownByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryBreakdownByDateRange, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownByDateRangeRow
	for rows.Next() {
		var i GetCategoryBreakdownByDateRangeRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryType,
			&i.Total,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCategoryIDAmountByDateRange = `-- name: GetTotalCategoryIDAmountByDateRange :one
SELECT COALESCE(SUM(t.amount),0) FROM transactions t
JOIN categories c ON t.category_id = c.id 
WHERE c.id = ?
AND t.transaction_date >=?
AND t.transaction_date < ?
`

type GetTotalCategoryIDAmountByDateRangeParams struct {
	ID                int64
	TransactionDate   string
	TransactionDate_2 string
}

func (q *Queries) GetTotalCategoryIDAmountByDateRange(ctx context.Context, arg GetTotalCategoryIDAmountByDateRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalCategoryIDAmountByDateRange, arg.ID, arg.TransactionDate, arg.TransactionDate_2)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getTotalCategoryTypeAmountByDateRange = `-- name: GetTotalCategoryTypeAmountByDateRange :one
SELECT COALESCE(SUM(t.amount),0) FROM transactions t
JOIN categories c ON t.category_id = c.id 
WHERE c.type = ?
AND t.transaction_date >=?
AND t.transaction_date < ?
`

type GetTotalCategoryTypeAmountByDateRangeParams struct {
	Type              string
	TransactionDate   string
	TransactionDate_2 string
}

func (q *Queries) GetTotalCategoryTypeAmountByDateRange(ctx context.Context, arg GetTotalCategoryTypeAmountByDateRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalCategoryTypeAmountByDateRange, arg.Type, arg.TransactionDate, arg.TransactionDate_2)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getTransactionByDateRange = `-- name: GetTransactionByDateRange :many
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE t.transaction_date >= ?
AND t.transaction_date < ? 
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetTransactionByDateRangeParams struct {
	TransactionDate   string
	TransactionDate_2 string
	Limit             int64
	Offset            int64
}

type GetTransactionByDateRangeRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionByDateRange(ctx context.Context, arg GetTransactionByDateRangeParams) ([]GetTransactionByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionByDateRange,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionByDateRangeRow
	for rows.Next() {
		var i GetTransactionByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE t.id = ?
`

type GetTransactionByIDRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.TransactionDate,
		&i.CategoryName,
		&i.CategoryType,
	)
	return i, err
}

const getTransactionsByCategoryID = `-- name: GetTransactionsByCategoryID :many
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE t.category_id = ?
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetTransactionsByCategoryIDParams struct {
	CategoryID int64
	Limit      int64
	Offset     int64
}

type GetTransactionsByCategoryIDRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionsByCategoryID(ctx context.Context, arg GetTransactionsByCategoryIDParams) ([]GetTransactionsByCategoryIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCategoryID, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByCategoryIDRow
	for rows.Next() {
		var i GetTransactionsByCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByCategoryType = `-- name: GetTransactionsByCategoryType :many
SELECT t.id, t.category_id, t.description,
    t.amount, t.transaction_date,
    c.name AS category_name, c.type AS category_type
FROM transactions t 
JOIN categories c 
ON t.category_id = c.id
WHERE c.type = ?
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type GetTransactionsByCategoryTypeParams struct {
	Type   string
	Limit  int64
	Offset int64
}

type GetTransactionsByCategoryTypeRow struct {
	ID              int64
	CategoryID      int64
	Description     string
	Amount          int64
	TransactionDate string
	CategoryName    string
	CategoryType    string
}

func (q *Queries) GetTransactionsByCategoryType(ctx context.Context, arg GetTransactionsByCategoryTypeParams) ([]GetTransactionsByCategoryTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCategoryType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByCategoryTypeRow
	for rows.Next() {
		var i GetTransactionsByCategoryTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.TransactionDate,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
