// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BackupDatabase(arg1:string):Promise<void>;

export function CreateCategory(arg1:models.CreateCategoryRequest):Promise<void>;

export function CreateTransaction(arg1:models.CreateTransactionRequest):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function EditCategory(arg1:models.EditCategoryRequest):Promise<void>;

export function EditTransaction(arg1:models.EditTransactionRequest):Promise<void>;

export function ExportTransactionsCSV():Promise<string>;

export function GenerateReport(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAllCategories():Promise<Array<models.CategoryResponse>>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetAllTransactions(arg1:number,arg2:number,arg3:string):Promise<models.PaginatedTransactions>;

export function GetAppSettings():Promise<models.AppSettings>;

export function GetCategoryUsageCount(arg1:number):Promise<number>;

export function GetDashboardData(arg1:string,arg2:string):Promise<models.DashboardData>;

export function GetSystemInfo():Promise<models.SystemInfo>;

export function GetTransactionByID(arg1:number):Promise<models.TransactionResponse>;

export function GetTransactionsByCategoryID(arg1:number,arg2:number,arg3:number):Promise<models.PaginatedTransactions>;

export function GetTransactionsByCategoryType(arg1:string,arg2:number,arg3:number):Promise<models.PaginatedTransactions>;

export function GetTransactionsByDateRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.PaginatedTransactions>;

export function PickBackupDestination():Promise<string>;

export function PickBackupSource():Promise<string>;

export function PickReportDestination():Promise<string>;

export function ResetAllData():Promise<void>;

export function ResetSettings():Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;
