// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function EditCategory(arg1) {
  return window['go']['main']['App']['EditCategory'](arg1);
}

export function EditTransaction(arg1) {
  return window['go']['main']['App']['EditTransaction'](arg1);
}

export function ExportTransactionsCSV() {
  return window['go']['main']['App']['ExportTransactionsCSV']();
}

export function GenerateReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2, arg3);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAllTransactions'](arg1, arg2, arg3);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetCategoryUsageCount(arg1) {
  return window['go']['main']['App']['GetCategoryUsageCount'](arg1);
}

export function GetDashboardData(arg1, arg2) {
  return window['go']['main']['App']['GetDashboardData'](arg1, arg2);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTransactionByID(arg1) {
  return window['go']['main']['App']['GetTransactionByID'](arg1);
}

export function GetTransactionsByCategoryID(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTransactionsByCategoryID'](arg1, arg2, arg3);
}

export function GetTransactionsByCategoryType(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTransactionsByCategoryType'](arg1, arg2, arg3);
}

export function GetTransactionsByDateRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTransactionsByDateRange'](arg1, arg2, arg3, arg4);
}

export function PickBackupDestination() {
  return window['go']['main']['App']['PickBackupDestination']();
}

export function PickBackupSource() {
  return window['go']['main']['App']['PickBackupSource']();
}

export function PickReportDestination() {
  return window['go']['main']['App']['PickReportDestination']();
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
